### PR TITLE
Show that `cache.start` must be called initially

### PR DESCRIPTION
**Pull request by jseppi**

### CODE REVIEW

**Comment by fhemberger** [comment]
You don't use `cache.start` in your request handler, but on server initialization. But thanks, I'll add this to the README.

**Comment by jseppi** [comment]
Oh right, good point. Thanks!

On Wed, Jul 1, 2015 at 3:07 PM, Frederic Hemberger <notifications@github.com

**Comment by fhemberger** [comment]
b0a316b38d74ceb1dec4db34b69fcb16acea005c should be ok to clarify the cache initialization. What do you think?

**Comment by jseppi** [comment]
:+1:

**Comment by fhemberger** [comment]
Ok thanks, closing this PR now …

**Pull request closed without merging**
